AWSTemplateFormatVersion: 2010-09-09
Description: this template provisions our dev network environment.
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Dev Network Configuration"
        Parameters: 
          - DevVPCCidrBlockPara
          - DevVPCenableDNSSupportPara
          - DevWebServerAZpara
          - DevWebServerSubnetCidrBlockpara
          - DevAppServerAZpara
          - DevAppServerSubnetCidrBlockpara
          - DevDBServerAZpara
          - DevDBServerSubnet
          - DevDBServerSubnetCidrBlockpara

Parameters: 
#Dev VPC parameters
  DevVPCCidrBlockPara:
    Description: please provide your Dev VPC CidrBlock
    Type: String
    Default: 10.0.0.0/16

  DevVPCenableDNSSupportPara:
    Description: pleas enable DNS Support (true/false)
    Type: String

# Web sever subnets parameters
  DevWebServerAZpara:
    Description: please provide availability zone for the web server
    Type: AWS::EC2::AvailabilityZone::Name

  DevWebServerSubnetCidrBlockpara:
    Description: Please provide a cidr block for your dev subnet
    Type: String

# App server subnets parameter
  DevAppServerAZpara:
    Description: please provide availability zone for the app server
    Type: AWS::EC2::AvailabilityZone::Name

  DevAppServerSubnetCidrBlockpara:
    Description: Please provide a cidr block for your app subnet
    Type: String

# database server subnet parameters
  DevDBServerAZpara:
    Description: Please select an avalaibity for the DB server
    Type: AWS::EC2::AvailabilityZone::Name

  DevDBServerSubnetCidrBlockpara:
    Description: Please a cidr block for your db server
    Type: String
 

Mappings: {}

Conditions: {}

Resources: 
  # Development VPC 
  DevVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref DevVPCCidrBlockPara
      EnableDnsSupport: !Ref DevVPCenableDNSSupportPara
      Tags:
        - Key: Name
          Value: DevVPC
  
  # Webserver subnet for dev VPC
  DevWebServerSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref DevWebServerAZpara
      VpcId: !Ref DevVPC
      CidrBlock: !Ref DevWebServerSubnetCidrBlockpara
      Tags:
        - Key: Name
          Value: WebServerSubnet

  # Appserver subnet for dev VPC
  DevAppServerSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref DevAppServerAZpara
      VpcId: !Ref DevVPC
      CidrBlock: !Ref DevAppServerSubnetCidrBlockpara
      Tags:
        - Key: Name
          Value: DevAppServerSubnet

  # Database subnet for dev VPC
  DevDBServerSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref DevDBServerAZpara
      VpcId: !Ref DevVPC
      CidrBlock: !Ref DevDBServerSubnetCidrBlockpara
      Tags:
        - Key: Name
          Value: DevDBServerSubnet
Outputs: {}