AWSTemplateFormatVersion: 2010-09-09
Description: "ec2 instance automation for our developement environment"
Metadata: {}

Parameters: 
  DevWebserverKeyName:
    Description: Please select your key pair
    Type: AWS::EC2::KeyPair::KeyName
  
  EnvironmentName:
    Description: Please select your choice environmment
    Type: String
    AllowedValues:
      - Dev
      - Prod 
      - Stage

Mappings: 
  DevWebserverGoldenAMImap:
    us-east-1:
      GoldenAMI: ami-0c7217cdde317cfec
    us-east-2:
      GoldenAMI: ami-05fb0b8c1424f266b

    us-west-1:
      GoldenAMI: ami-0ce2cb35386fc22e9
    us-west-2:
      GoldenAMI: ami-008fe2fc65df48dac
    

Conditions: 
  CreateDevStageProdResources:
    !Equals [!Ref EnvironmentName, Prod]

Resources: 
  DevWebserver1:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref DevWebserverKeyName
      ImageId: !FindInMap [ DevWebserverGoldenAMImap, !Ref 'AWS::Region', GoldenAMI ]
      InstanceType: t2.micro
      Monitoring: true
      UserData: !Base64 |
        #!/bin/bash -ex
        sudo su
        apt update -y
        apt -y install apache2
        systemctl start apache2
        systemctl enable apache2
        apt install wget -y
        wget https://github.com/awanmbandi/google-cloud-projects/raw/jjtech-flix-app/jjtech-streaming-application-v1.zip 
        apt install unzip -y
        unzip jjtech-streaming-application-v1.zip
        rm -f /var/www/html/index.html
        cp -rf jjtech-streaming-application-v1/* /var/www/html/
      Tags: 
        - Key: Name
          Value: evWebserver1

  DevWebserver2:
    Type: AWS::EC2::Instance
    Condition: CreateDevStageProdResources
    Properties:
      KeyName: !Ref DevWebserverKeyName
      ImageId: !FindInMap [ DevWebserverGoldenAMImap, !Ref 'AWS::Region', GoldenAMI ]
      InstanceType: t2.micro
      Monitoring: true
      UserData: !Base64 |
        #!/bin/bash -ex
        sudo su
        apt update -y
        apt -y install apache2
        systemctl start apache2
        systemctl enable apache2
        apt install wget -y
        wget https://github.com/awanmbandi/google-cloud-projects/raw/jjtech-flix-app/jjtech-streaming-application-v1.zip 
        apt install unzip -y
        unzip jjtech-streaming-application-v1.zip
        rm -f /var/www/html/index.html
        cp -rf jjtech-streaming-application-v1/* /var/www/html/
      Tags: 
        - Key: Name
          Value: evWebserver2

  DevWebserver3:
    Type: AWS::EC2::Instance
    Condition: CreateDevStageProdResources
    Properties:
      KeyName: !Ref DevWebserverKeyName
      ImageId: !FindInMap [ DevWebserverGoldenAMImap, !Ref 'AWS::Region', GoldenAMI ]
      InstanceType: t2.micro
      Monitoring: true
      UserData: !Base64 |
        #!/bin/bash -ex
        sudo su
        apt update -y
        apt -y install apache2
        systemctl start apache2
        systemctl enable apache2
        apt install wget -y
        wget https://github.com/awanmbandi/google-cloud-projects/raw/jjtech-flix-app/jjtech-streaming-application-v1.zip 
        apt install unzip -y
        unzip jjtech-streaming-application-v1.zip
        rm -f /var/www/html/index.html
        cp -rf jjtech-streaming-application-v1/* /var/www/html/
      Tags: 
        - Key: Name
          Value: evWebserver3

Outputs:  {}